version: '3.8'

services:
  businessmap-mcp:
    build: .
    environment:
      - BUSINESSMAP_API_URL=${BUSINESSMAP_API_URL:-https://your-instance.kanbanize.com/api/v2}
      - BUSINESSMAP_API_TOKEN=${BUSINESSMAP_API_TOKEN}
      - BUSINESSMAP_DEFAULT_WORKSPACE_ID=${BUSINESSMAP_DEFAULT_WORKSPACE_ID:-1}
      - BUSINESSMAP_READ_ONLY_MODE=${BUSINESSMAP_READ_ONLY_MODE:-false}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-businessmap-mcp}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-1.0.0}
      - SSE=${SSE:-false}
      - STREAMABLE_HTTP=${STREAMABLE_HTTP:-true}
      - PORT=${PORT:-3002}
    ports:
      - "${PORT:-3002}:3002"
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: nginx proxy for HTTP transport
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - businessmap-mcp
    profiles:
      - with-proxy 